name: Model_Components_dispatch

on:
  repository_dispatch:
    types:
      - model_components

jobs:
  process-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download from Airtable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            python .github/libs/model_components.py ${{github.event.client_payload.key}}



      - name: Create Pull Request
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_USERNAME: wolfiex
        run: |

            git config --global user.email "actions@wcrp-cmip.org"
            git config --global user.name "CMIP-IPO GitHub Automation"

            git add -A 
            git commit -m 'Automated update to model_components'
            git push

            # base_branch="main"
            # feature_branch="feature-branch"

            # git config --global user.email "${GITHUB_USERNAME}@users.noreply.github.com"
            # git config --global user.name "${GITHUB_USERNAME}"

            # gh pr create --base $base_branch --head $feature_branch --title "Automated PR to Main" --body "This pull request was automatically created by a GitHub Actions workflow." --reviewer $GITHUB_USERNAME
      
