name: New Consortium

on:
  issues:
    types: [opened, edited]

jobs:
  process_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read issue title
        id: read_title
        run: echo "::set-output name=title::${{ github.event.issue.title }}"

      - name: Read issue body
        id: read_body
        run: echo "::set-output name=body::${{ github.event.issue.body }}"

      - name: Read issue submitter
        id: read_submitter
        run: echo "::set-output name=submitter::${{ github.event.issue.user.login }}"

      - name: Determine script to run
        id: determine_script
        run: |
          title=$(echo "${{ steps.read_title.outputs.title }}" | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          if [[ "$title" == *"Add Consortium"* ]]; then
            echo "::set-output name=script::add/consortium.py"
          else
            # echo "::set-output name=script::default_script.py"
            echo ""
          fi



      - name: Run Python script
        id: run_python
        env:
          ISSUE_TITLE: ${{ steps.read_title.outputs.title }}
          ISSUE_BODY: ${{ steps.read_body.outputs.body }}
          ISSUE_SUBMITTER: ${{ steps.read_submitter.outputs.submitter }}
        run: |
          out=python ".github/libs/${{ steps.determine_script.outputs.script }}"
          echo "::set-output name=outname::$out"
          


      - name: Create branch
        run: |
          
          title=$(echo "${{ steps.run_python.outputs.outname }}" | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          # title=$(echo "${{ steps.read_title.outputs.title }}" | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          git checkout -b "$title"

          
