name: New Consortium Processing

on:
  issues:
    types: [opened, edited]

jobs:
  process_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read issue details
        id: read_issue
        run: |
          echo "::set-output name=title::${{ github.event.issue.title }}"
          # echo "::set-output name=body::${{ github.event.issue.body }}"
          echo "::set-output name=submitter::${{ github.event.issue.user.login }}"

      - name: Determine script to run
        id: determine_script
        run: |
          title=$(echo "${{ steps.read_issue.outputs.title }}" | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          # this flattens the title and removed spaces, punctuation and case
          if [[ "$title" == *"addconsortium"* ]]; then
            echo "::set-output name=script::add/consortium.py"
          else
            echo "default"
          fi

      - name: Run Python script
        id: run_python
        env:
          ISSUE_TITLE: ${{ steps.read_issue.outputs.title }}
          ISSUE_BODY: github.event.issue.body
          # pipe should preseve newline properties for multilines
          ISSUE_SUBMITTER: ${{ steps.read_issue.outputs.submitter }}
        run: |
          script="${{ steps.determine_script.outputs.script }}"
          if [ "$script" == "default" ]; then
            echo "No specific script found for this issue."
          else
            python ".github/libs/$script" 
          fi

      - name: Create branch
        run: |
          title=$(echo "${{ steps.read_issue.outputs.title }}" | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          git checkout -b "$title"
